// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALwKNTkOI_IvRSuvHo2e0cNv8gU6pkGgg',
    appId: '1:861470710409:web:afced8f3b8fd4c74a2c458',
    messagingSenderId: '861470710409',
    projectId: 'flutter-chat-application-7cfbb',
    authDomain: 'flutter-chat-application-7cfbb.firebaseapp.com',
    storageBucket: 'flutter-chat-application-7cfbb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDb99KWnhHTtssoQ8tcOgtWRZTU2k-y_10',
    appId: '1:861470710409:android:1e7700b143cbef5da2c458',
    messagingSenderId: '861470710409',
    projectId: 'flutter-chat-application-7cfbb',
    storageBucket: 'flutter-chat-application-7cfbb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYwl6pJjs2LBQixWnww2H4ne8EC5iBd10',
    appId: '1:861470710409:ios:b81da0387aaa03a5a2c458',
    messagingSenderId: '861470710409',
    projectId: 'flutter-chat-application-7cfbb',
    storageBucket: 'flutter-chat-application-7cfbb.appspot.com',
    iosBundleId: 'com.example.flutterTextChatAppilication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYwl6pJjs2LBQixWnww2H4ne8EC5iBd10',
    appId: '1:861470710409:ios:e71595b6a6a3e067a2c458',
    messagingSenderId: '861470710409',
    projectId: 'flutter-chat-application-7cfbb',
    storageBucket: 'flutter-chat-application-7cfbb.appspot.com',
    iosBundleId: 'com.example.flutterTextChatAppilication.RunnerTests',
  );
}
